- Modding/mounts.md
Matches new engine mounting code.
> Update mounts.md to match new filesystem mounting

- docs/Reference/sound_operators.md
This is pretty basic documentation automatically dumped from the game.
> Add reference documentation for the available SOS operators

- _config.yml
> fix: edit on github link points to the right url

- .gitignore
- Gemfile
- docs/Reference/bspsupport.md
- docs/Reference/vscript.md
Adds autogenerated documentation exported using `document.nut` from p2ce. Anything that is specific to P2CE has been marked as such. We'll probably need a better method of generating documentation like this in the future though.
> Add vscript docs 

- docs/Reference/vscript.md
Adds 3 new VScript functions that were merged into the engine earlier
> feat: Add GetPartner and EyeAngles

- docs/Reference/vscript.md
A new parameter was added to disable transforming the end pos.
(PSC-support chat in P2CE's discord server).
> Add the boolean parameter to TracePortalLine (doc)

- docs/Reference/vscript.md
Hopefully everything is correct, but please check for any mistakes.
> Update documentation on vscript functions.

- pages/p2ce/meta.json
- pages/shared/modding/sounds.md
Went through and cleaned up p2ce's meta.json.
Also documented some details about our sound system, such as supported file formats, sample rates and the sound script format.
> Update p2ce meta.json + sound system docs

- pages/shared/vscript/global/functions.md
Just added parameter names to make things a bit more clear
> feat: Update function signatures for globals

- pages/shared/vscript/global/constants.md
> feat: update constants a bit

- pages/shared/reference/launchoptions.md
Does as the title says.
It would be good to write up a full article on how to use the dedicated server at some point, including how to install the game using SteamCMD.
> Document the launch args `-dedicated` and `-nousermount`

- LICENSE.md
> change year to 2024

- run.bat
- run.sh
This PR adds a batch and bash script to just easily get started with running the wiki. Hopefully this should make it easier for anyone who wants to try to contribute to preview their work.
> Add easy startup scripts

- pages/momentum/meta.json
- pages/p2ce/meta.json
- pages/shared/angelscript/hammer/classes.md
- pages/shared/angelscript/hammer/enums.md
- pages/shared/angelscript/hammer/example.md
- pages/shared/angelscript/hammer/global_functions.md
- pages/shared/angelscript/hammer/global_properties.md
- pages/shared/angelscript/hammer/index.md
- pages/shared/angelscript/hammer/value_types.md
- pages/shared/angelscript/index.md
- pages/shared/meta.json
Currently just a basic duplication, open to suggestions on any edits that people might see fit to these pages.
Goal is to just fill out part of #17 right now and get more information regarding Strata Source itself onto the Strata Source wiki.
> [AngelScript] Hammer AS Documentation from Momentum Docs

- pages/shared/index.md
Added a couple things, that's it.
> feat: Update feature list with a couple more things

- pages/shared/index.md
> feat: Add more features

- pages/shared/index.md
> fix: change portal revolution link on homepage

- pages/shared/panorama/snippets.md
- pages/shared/reference/launchoptions.md
Good to have some quick reference, because I frequently forget how to use them.
> Document Panorama snippets

- pages/shared/vscript/class/CBasePlayer.md
- pages/shared/vscript/global/constants.md
Document the new `CBasePlayer::GetButtons` method and the `IN_` button flags
> feat: Document GetButtons VScript method and the IN_ flags

- pages/shared/vscript/global/functions.md
This was added way back in 2022, but I forgot to document it...apparently?
> feat: Document CreateEntityByName, finally

- pages/shared/vscript/global/functions.md
Document a couple more things that I missed apparently.
> feat: Document more missing VScript functions

- pages/shared/vscript/class/CBaseAnimating.md
- pages/shared/vscript/class/CBaseEntity.md
- pages/shared/vscript/global/constants.md
Only merge this once the internal PR is merged
> feat: Document the new VScript methods

- pages/shared/vscript/class/CBaseEntity.md
Do not merge until the internal pull request is merged
> feat: Document IsBSPModel

- docs/modding/overview/vtf-v76.md
I'd like to expand this page to the entire format at some point, but this is a start
> feat: initial VTF docs

- docs/panorama/overview/dialog-variables.md
I made a mistake on modifier usage :(
> Fix dialog variable modifer usage

- docs/modding/overview/about.md
- docs/modding/overview/bsp-v25.md
v2 was introduced with clustered
> Document new worldlights lump version

- docs/modding/overview/vtf-hotspot-resource.md
Copied the hotspot resource spec from the gist to here
> feat: Hotspot VTF resource

- dumps/vscript.json
Lots of random changes got included here due to the nature of these doc dumps.
Please do not merge until the CLight stuff has been merged internally. thx.
> chore: 2025-06-25 update to VScript docs

- docs/modding/overview/vtf-hotspot-resource.md
- docs/modding/overview/vtf-hotspot-text-format.md
I'd also like to write a page on how to use hotspots at some point, but this should be enough to get started with
> Reword hotspot format page, add text format page

- docs/modding/overview/p2ce-mod-template.md
This PR adds an article for making sourcemods for P2:CE (where to download the template, its contents, etc.)
> Add article for Portal 2: Community Edition's mod template

- docs/modding/overview/p2ce-mod-template.md
> Miscellaneous fixes to p2ce-mod-template.md
